### ISSUE TITLE
Partial attachments downloading

### ISSUE THREAD

**Issue by ddsmes** [roundcube/roundcubemail#5232]
When attachment is

`Content-Transfer-Encoding: base64`

and there is NO empty line AFTER base64 data
then RoundCube (version 1.1.5 tested) gives client partial attacment downloading
ForEx:
if i have message with
`Content-Type: multipart/mixed;boundary="===7870669===="`
`.....`
`--===7870669====`
`Content-Type: application/vnd.openxmlformats-officedocument.wordprocessingml.document`
`Content-Disposition: attachment;`
` filename="file.pdf"`
`Content-Transfer-Encoding: base64`

`UEsDBBQABgAIAAAAIQAFMwonoQEAAMoGAAATAAgCW0NvbnRlbnRfVHlwZXNdLnhtbCCiBAIo`
`oAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA`
`.....`
`AAAAAADKggEAd29yZC9mb250VGFibGUueG1sUEsBAi0AFAAGAAgAAAAhAKkKJemGAQAA1AIA`
`ABAAAAAAAAAAAAAAAAAAiIUBAGRvY1Byb3BzL2FwcC54bWxQSwUGAAAAAA8ADwDNAwAARIgB`
`AAAA`
`--===7870669====`
then RoundCube downloads PARTIAL attachment. It takes content between `boundary`, drops (!!!) last (NOT EMPTY!!!) line and decodes PARTIAL base64-data.

When i put manually empty line at the end of base64-data - all OK.

Other imap-clients, like Thunderbird, AppleMail etc have no problems with such email files

**Comment by alecpl** [comment]
This may be IMAP server issue. What IMAP server/version? See if ```$config['imap_disabled_caps'] = array('BINARY');``` resolves the issue.

**Comment by ddsmes** [comment]
Thanx.
`$config['imap_disabled_caps'] = array('BINARY');`
fixed problem

**Comment by winicius87** [comment]
This issue is still in roundcubemail. I cannot download the file completely when I upload with curl.
