### ISSUE TITLE
Decrypted mailvelope mails show "encrypted.asc"

### ISSUE THREAD

**Issue by sophie-h** [roundcube/roundcubemail#5279]
Viewing mailvelope dencrypted pgp emails show an `encrypted.asc` attachment. Probably, this will be confusing for "average" users.

There could still be unencrypted attachments. Maybe it is possible to remove the `encrypted.asc` (or corresponding attachement) from the list and hide the list if empty?

**Comment by alecpl** [comment]
When using Enigma such attachments aren't displayed. So, indeed that makes sense.

**Comment by alecpl** [comment]
Sorry, my mistake. It looks like Enigma does not hide such attachments either.

**Comment by thomascube** [comment]
Decryption with Mailvelope may fail for various reasons. Therefore it might be useful to have the possibility to download the encrypted part and decrypt it for example with a locally installed tool.

Thunderbird (with Enigma plugin) also keeps the attachment list unaltered, even if decryption was successful.

**Comment by qua-bla** [comment]
> it might be useful to have the possibility to download the encrypted part

Absolutely. I was thinking about marking the (inline) attachment passed to Mailvelope and remove it on successful decryption via Mailvelope. However, looking at the Mailvelope API this information is not disclosed. As a last resort the attachment could be hidden as default and displayed on Mailvelope errors. This sounds sufficiently complicated to me to abandon the approach.

However, a "decrypted.asc" attachment will confuse users, as many things related to PGP will do. (This is based on observing people using Enigmail). My goal is to get as many confusing parts out of the way as possible.

I would like to suggest the following options
1. Give the attachment a nice looking icon, maybe an explanation (looks like even this might be non-trivial, since the attachments Content-Type is not directly `application/pgp-encrypted`?)
2. Place the attachment window differently (less prominent), if only the content passed to Mailvelope is part of the attachment list. Maybe place it below the Mailvelope window.

If this sounds reasonable to you, I could try to help implementing this.

**Comment by alecpl** [comment]
Actually Thunderbird with Enigmail do not display these attachments at all. Nor for successfully encrypted, nor for failures. Now I checked again, Roundcube's Enigma also hides them (it displays only signature attachments).
So, we should consider hiding them. Definitely a nice icon would be the less we should do.

**Comment by thomascube** [comment]
Decryption success of failure on Mailvelope cannot be detected due to [Mailvelope issue #334](https://github.com/mailvelope/mailvelope/issues/334) and thus for now we should leave the attachment list untouched. Better icon is on the way...

**Comment by alecpl** [comment]
Done.

**Comment by thomascube** [comment]
I don't consider this issue closed yet. Some progress is being made on the Mailvelope side but still not satisfying: https://github.com/mailvelope/mailvelope/pull/386

**Comment by alecpl** [comment]
Mailvelope 1.6.0 is already released. Here's a sample on how to catch errors:
```diff
--- a/program/js/app.js
+++ b/program/js/app.js
@@ -3806,9 +3806,15 @@ function rcube_webmail()
   // wrapper for the mailvelope.createDisplayContainer API call
   this.mailvelope_display_container = function(selector, data, keyring, msgid)
   {
-    mailvelope.createDisplayContainer(selector, data, keyring, { showExternalContent: this.env.safemode }).then(function() {
-      $(selector).addClass('mailvelope').children().not('iframe').hide();
+    mailvelope.createDisplayContainer(selector, data, keyring, { showExternalContent: this.env.safemode }).then(function(status) {
       ref.hide_message(msgid);
+      if (status.error && status.error.message) {
+        ref.display_message(status.error.message, 'error');
+        $(selector + ' > iframe').remove();
+      }
+      else {
+        $(selector).addClass('mailvelope').children().not('iframe').hide();
+      }
       setTimeout(function() { $(window).resize(); }, 10);
     }, function(err) {
       console.error(err);
```
TODO: 1) remove .asc attachment on decryption success, 2) fix mailvelope iframe blinking on error (probably we should hide the iframe by default and "show" it on decryption success).

**Comment by alecpl** [comment]
Done.
