### ISSUE TITLE
unknown column created

### ISSUE THREAD

**Issue by m4ri01** [roundcube/roundcubemail#5479]
anyone know why column created is missing on table session? this is the warn that i get from roundcube installer. 
DB Write:  NOT OK([1054] Unknown column 'created' in 'field list' (SQL Query: INSERT INTO `session` (`sess_id`, `created`, `ip`, `vars`) VALUES ('7064d8839677ef7381b047d68a1fb082', now(), '127.0.0.1', 'foo')))

**Comment by alecpl** [comment]
This column has been removed in git-master version. What exactly are you doing?

**Comment by alecpl** [comment]
Oops. Looks like a real bug. Indeed the query used for testing write privileges need to be updated.

**Comment by alecpl** [comment]
Fixed.

**Comment by Ubunthon** [comment]
I'm still seeing this issue even after implementing the code changes

`[14-Dec-2016 12:12:04 -0800]: <6078bi8f> DB Error: [1054] Unknown column 'created' in 'field list' (SQL Query: INSERT INTO `session` (`sess_id`, `vars`, `ip`, `created`, `changed`) VALUES ('6078bi8f8frm6d1r6o0fsmkeb2', 'dGVtcHxiOjE7bGFuZ3VhZ2V8czo1OiJlbl9VUyI7dGFza3xzOjU6ImxvZ2luIjs=', '172.68.34.94', now(), now())) in /usr/share/roundcube/program/lib/Roundcube/rcube_db.php on line 539 (GET /)`

` protected function handle_error($query)
    {
        $error = $this->dbh->errorInfo();

        if (empty($this->options['ignore_key_errors']) || !in_array($error[0], array('23000', '23505'))) {
            $this->db_error = true;
            $this->db_error_msg = sprintf('[%s] %s', $error[1], $error[2]);

            rcube::raise_error(array('code' => 500, 'type' => 'db',
                'line' => __LINE__, 'file' => __FILE__,
                'message' => $this->db_error_msg . " (SQL Query: $query)"
                ), true, false);
        }`


Line 539 is:  'line' => __LINE__, 'file' => __FILE__,

**Comment by alecpl** [comment]
As you can see in my commit there's no reference to `created` column anymore. So, looks like you didn't update the file. Or you're trying to use Roundcube 1.2 code with database from git-master. That will not work.
