### ISSUE TITLE
Roundcube treats images defined as data URIs in CSS as evil

### ISSUE THREAD

**Issue by netesa** [roundcube/roundcubemail#5580]
I have the following email notification message:
[test.zip](https://github.com/roundcube/roundcubemail/files/684468/test.zip)

I observe two issues in the way Roundcube renders it. First, it is detected as referencing remote images, which is not true:
![rc-1](https://cloud.githubusercontent.com/assets/6199148/21641130/2a40f308-d27a-11e6-894c-6582fe5657f7.png)

Then, after confirming (clicking "Display images") it also not rendered correctly because png images defined as data URIs in CSS are treated as evil and the whole class definitions are removed:
![rc-2](https://cloud.githubusercontent.com/assets/6199148/21641200/a2b63fdc-d27a-11e6-912c-a2e007f4eae6.png)

Desktop mail clients diplay this message correctly immediately and without any warnings, for instance Thunderbird:
![thunderbird](https://cloud.githubusercontent.com/assets/6199148/21641231/cfb112fa-d27a-11e6-9a0d-ed1902becaf8.png)

**Comment by alecpl** [comment]
Fixed.

**Comment by netesa** [comment]
This is still **not fixed** in case where the message contains image data URIs and also references a remote image. Everything is fine until you click "Display images".

A test message: [test.zip](https://github.com/roundcube/roundcubemail/files/1346750/test.zip)

**Comment by alecpl** [comment]
Confirmed.

**Comment by alecpl** [comment]
Fixed.
