### ISSUE TITLE
Signature below the quoted message

### ISSUE THREAD

**Issue by bukowski12** [roundcube/roundcubemail#5628]
Hi
In last firefox 51 when i reply email, signature is below the quoted message Although checkbox is not selected. In Chrome is it ok.

**Comment by alecpl** [comment]
What Roundcube version? What mode, html or plain text?

**Comment by bukowski12** [comment]
Roundcube version 1.1.7,  signature is plain text.

**Comment by alecpl** [comment]
and you reply in plain text too?

**Comment by bukowski12** [comment]
Yes the email which I answered was plain text.

**Comment by alecpl** [comment]
Ok, but I'd also need to know all your Signature Options settings + "When replying" setting.

**Comment by bukowski12** [comment]
![roundcube_setting](https://cloud.githubusercontent.com/assets/1533077/22465779/a98bf2cc-e7bd-11e6-8f78-f14cb2b56f10.png)

**Comment by alecpl** [comment]
Confirmed with git-master. There's no issue in HTML mode.

**Comment by alecpl** [comment]
Fixed.

**Comment by lingfude** [comment]
Tested on Firefox 51.0,1 and the problem persists.
The signature is always below the quoted message even if "Place signature below the quoted message" is unchecked.

**Comment by thueske** [comment]
Can confirm this, @lingfude - not working (tested with 1.1.x release).

**Comment by alecpl** [comment]
What are you talking about? Did you apply the patch? It definitely fixed the issue for me.

**Comment by thueske** [comment]
Yes, I applied the [patch](f8e0e1d4eddc7ac2f9133ad67b8733fcbef91209) to 1.1.x, but the signature position is not correct. Also tried version 1.2.x, which ironically works.

**Comment by thueske** [comment]
Figured out that minified javascript file is not generated automatically - fixed that and now everything works. Thanks.

**Comment by lingfude** [comment]
Hi Alec.
I'm using version 1.2.3 and I applied only this [patch](https://github.com/roundcube/roundcubemail/commit/a336026142f182202163e351e920b7a39a5eaa6c).
Do I need apply anything else?

**Comment by helmo** [comment]
You can use `bin/jsshrink.sh` to generate new minified javascript files.

**Comment by lingfude** [comment]
@helmo, thanks.
It's working now.
