### ISSUE TITLE
Google Analytics

### ISSUE THREAD

**Issue by stefanogironella** [roundcube/roundcubemail#5748]
Hi, I've noticed a strange behavior in address-book, while writing a new message.

Hi have many contacts in my address book, but when i click to a contact group (expecting to list all contacts within selected group) i always get an empty list.

Seems that ./program/steps/mail/list_contacts.inc (line 83) search for '_gid' within GET, POST and COOKIES to lookup selected contacts-group.:

`if ($group_id = rcube_utils::get_input_value('_gid', rcube_utils::INPUT_GPC)) {`

Problem is that Google Analytics has already defined a '_gid' cookie, so Roundcube is searching for contacts associated to group 'GA1.1.1497906129.1493798310' (for example), which obviously doesn't exists.

Isn't possibile to have Roundcube search only within GET parameters in this action?

**Comment by stefanogironella** [comment]
For the moment I've applied an hot-fix, changing:

if ($group_id = rcube_utils::get_input_value('_gid', rcube_utils::INPUT_GPC)) {
    $CONTACTS->set_group($group_id);
}
// list groups of this source (on page one)
else if ($CONTACTS->groups && $CONTACTS->list_page == 1) {
    $jsresult = rcmail_compose_contact_groups($CONTACTS, $source);
}

to
if ($group_id = rcube_utils::get_input_value('_gid', rcube_utils::INPUT_GET)) {
    $CONTACTS->set_group($group_id);
}
elseif ($group_id = rcube_utils::get_input_value('_gid', rcube_utils::INPUT_POST)) {
    $CONTACTS->set_group($group_id);
}
// list groups of this source (on page one)
else if ($CONTACTS->groups && $CONTACTS->list_page == 1) {
    $jsresult = rcmail_compose_contact_groups($CONTACTS, $source);
}

**Comment by alecpl** [comment]
As I see using only GET should be ok.

**Comment by alecpl** [comment]
Fixed in a couple of additional places.

**Comment by tomsommer** [comment]
Can we get this in a patch-release, it's pretty breaking across the releases.

**Comment by goncruz** [comment]
I second this request, I'm also also having this problem with 1.2.5. In the meanwhile I'll use  stefanogironella's fix. Thanks.

**Comment by dol** [comment]
A backport of this bug to 1.1 and 1.2 would be nice. We have several customer reports regarding this issue.
@stefanogironella nice catch and thank you.

**Comment by dol** [comment]
We deployed a Apache header cleanup to fix the issue:

```
<IfModule mod_headers.c>
    RequestHeader edit Cookie "(^\s*_gid=[^;]*;|;\s*_gid=[^;]*)" ""
</IfModule>
```

It's not ideal to perform a header filtering for each request, but it does the trick.

**Comment by thueske** [comment]
@stefanogironella's change does not fix the issue for me when working with version 1.1.x - any ideas?
