### ISSUE TITLE
Release 1.3.1 / no cursor in reply window (HTML mode)

### ISSUE THREAD

**Issue by faf2019** [roundcube/roundcubemail#5969]
Hi,

In the release 1.2, i had the cursor in the reply window into the HTML editor area but it does'nt work anymore in 1.3.1.

The cursor is visible in Text mode reply only.

Any suggestion ?
Best regards.

**Comment by alecpl** [comment]
What browser? Any errors in browser console? Did you try with disabled all plugins?

What do you mean exactly? There's no cursor after you click the editor area or you expect the cursor to be placed there initially? Can you write anything in the editor?

**Comment by faf2019** [comment]
I tried with Chrome 61, Chromium 61, Firefox 55 (All on Ubuntu).
No error in the console. Cache deleted.
No plugin.

I have set a signature.

You can see the cursor in plain text mode :
![capture-3](https://user-images.githubusercontent.com/32289337/30846931-d7364b90-a299-11e7-8f78-b5f31594c076.png)

But no cursor in HTML mode :
![capture-4](https://user-images.githubusercontent.com/32289337/30846946-e8f3f0b2-a299-11e7-86d1-de5adf43b7bf.png)

**Comment by faf2019** [comment]
---
Stéphane Escaich ~ OVENSIA
144 rue de la Cassardière
44115 BASSE GOULAINE
Tel. +33 9 52 11 68 68
Fax. +33 9 57 11 68 68
Mob. +33 6 68 65 05 09
Mel. stephane@ovensia.fr
Web. http://www.ovensia.fr 

Le 26/09/2017 08:39, Aleksander Machniak a écrit :

> What browser? Any errors in browser console? Did you try with disabled all plugins? 
> 
> What do you mean exactly? There's no cursor after you click the editor area or you expect the cursor to be placed there initially? Can you write anything in the editor? 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].

Enregistrer 

Enregistrer 

Links:
------
[1]
https://github.com/roundcube/roundcubemail/issues/5969#issuecomment-332101137
[2]

**Comment by alecpl** [comment]
Fixed.

**Comment by faf2019** [comment]
Thank you Alec.

**Comment by Skygge666** [comment]
@faf2019: Can you confirm the fix is working? I still can't see cursor in the editor, though I installed (three times to be sure) current master version from github...

**Comment by Skygge666** [comment]
The editor is focused, but the cursor appears AFTER typing first letter. Example: highlight e-mail, click reply, start typing "Hello!" As a result you will have "ello!"... :(

**Comment by faf2019** [comment]
@Skygge666
I can confirm. No cursor in HTML mode reply with version 1.3.1 on a fresh install.

**Comment by alecpl** [comment]
This fix didn't go to 1.3.1, it will be in 1.3.2.
