### ISSUE TITLE
PHP Warning:  Use of undefined constant IDNA_DEFAULT

### ISSUE THREAD

**Issue by teoberi** [roundcube/roundcubemail#6244]
My configuration:
PHP-7.2.4
Roundcube-1.3.6
After updating Roundcube 1.3.5 -> 1.3.6 in mailog the message appears:

> Apr 12 09:58:14 mail roundcube: PHP Warning:  Use of undefined constant IDNA_DEFAULT - assumed 'IDNA_DEFAULT' (this will throw an Error in a future version of PHP) in /var/www/htdocs/roundcube/program/lib/Roundcube/rcube_utils.php on line 908

**Comment by alecpl** [comment]
Damn, my fault. If you install php-intl extension it will disappear.

**Comment by alecpl** [comment]
Fixed.

**Comment by workpaul** [comment]
I still have the same issue in centos 7.4 with php 7.2.6-1. Any other ideas?

**Comment by alecpl** [comment]
There's only two solutions for this. Install php-intl extension or fix the code as in https://github.com/roundcube/roundcubemail/commit/8477b881e55.

**Comment by workpaul** [comment]
Thanks a lot. Indeed, the problem was related to the php7.2 configuration.
