### ISSUE TITLE
Start new mail while sending is in progress

### ISSUE THREAD

**Issue by zoobag** [roundcube/roundcubemail#6470]
There is problem in roundcube to start new mail or reply while mail sending in progress. There is no problem to start new mail before and after sending, only if sending is in progress. I get every time an error and we think there is some problems with session handling in roundcube.

When sending is in progress and you try to start new mail, roundcube doesn't start new session like it would be if you start new mail not while sending is in progress. So the session doesn't exist any more when the mail is sent and you can't send or save a new mail.

**Comment by alecpl** [comment]
So, you use a separate window/tab to send a mail, leave it open while sending and choose new mail/reply from the other window? What are your session settings in Roundcube config? Any errors in log? Any errors in browser console? What browser? What plugins? What PHP version?

**Comment by alecpl** [comment]
Settings are in config/config.inc.php. Also try with disabled all plugins, please.

**Comment by zoobag** [comment]
disable plugins in the config?

this is my config now:

$config = array();
$config['enable_installer'] = true;
$config['db_dsnw'] = 'mysql://roundcubemail:xxxxxxx@127.0.0.1/roundcubemail';
$config['default_host'] = '127.0.0.1';
$config['default_port'] = 144;
$config['smtp_server'] = '127.0.0.1';
$config['smtp_port'] = 25;
$config['smtp_user'] = '%u';
$config['smtp_pass'] = '%p';
$config['support_url'] = '';
$config['product_name'] = 'Webmail';
$config['des_key'] = 'xxxxxxxxxxxx';

$config['plugins'] = array(
    'archive',
    'zipdownload',
    'newmail_notifier',
    'persistent_login',
    'contextmenu',
    'managesieve',
    'thunderbird_labels',
    'automatic_addressbook',
    'carddav',
    'xcalendar',
);

$config['skin'] = 'larry';
$config['mime_types'] = '/usr/local/etc/nginx/mime.types';

$config['autocomplete_threads'] = '3';
$config['autoexpand_threads'] = '1';

$config['enable_spellcheck'] = false;
$config['debug_level'] = 1;
$config['enable_caching'] = false;
//$config['session_storage'] = 'redis';
//$config['redis_session ='] = array( 'unix:///tmp/redis.sock' );
//$config['session_storage'] = 'memcached';
$config['session_storage'] = 'php';
//$config['redis_session ='] = array( 'unix:///tmp/memcached.sock' );

**Comment by alecpl** [comment]
I think this is caused by session_storage=php. The php session is locking, so it will not allow to read/write to session until previous request finished. There's probably no solution for this other than to use other sessions_storage method.

**Comment by zoobag** [comment]
Ok, thank you! Does it happens in your case, can you reproduce it? What I better should take - redis or memcached?

**Comment by alecpl** [comment]
I can reproduce the error even with 'db' session. So, it's definitely something we'd like to fix.

**Comment by alecpl** [comment]
Fixed.

**Comment by zoobag** [comment]
After update and fix it is still not possible to start new mail if the sending is in progress.

**Comment by zoobag** [comment]
Same problem after upgrading to 1.4.11 and the issue was resolved for me before in 1.4.10. But now the problem #6470  is back.
