### ISSUE TITLE
Prevent error from logs getting tmp file

### ISSUE THREAD

**Issue by dddns** [roundcube/roundcubemail#6657]
Howdy,

Just to make a better handle of this, i have a tail on the logs everyday and I've been seeing this below.
Maybe just an if before to make sure the file exists so that the error doesn't exist.
I have no idea how to reproduce it, I just tail the logs!
Intention of the report is to make better handle of it.

Running 1.3.8

Thanks,

===
Mar  3 12:50:15 fastweb roundcube: PHP Warning:  file_get_contents(/home/hosting/dg.pt/webmail/temp/97eb4111280c4f60f9d32a33ea73d513.tmp): failed to open stream: No such file or directory in /home/hosting/dg.pt/webmail/program/steps/mail/get.inc on line 533

**Comment by alecpl** [comment]
Looks like the temp file might be removed in-between. Maybe fixed with b1a3d46f892fe, but hard to be sure without precise steps to reproduce the issue.

**Comment by dddns** [comment]
Hi Alec,

Well, will be hard to tell you, have no idea how it happened.
But in the next release I'll keep looking for this to see if still happens.

There will be an 1.3.9 or 1.3.8 will jump to 1.4?
That fix is included in any of those right?

**Comment by alecpl** [comment]
I see now that the fix has been backported to 1.3.2. So, it must be another issue. We'll need a way to reproduce.

ps. There will be 1.3.9 at some point (maybe after 1.4.0).

**Comment by dddns** [comment]
Alec,

Thanks, I'll try to investigate more to see how it happens.

**Comment by alecpl** [comment]
Any news on this?

**Comment by dddns** [comment]
Hi Alec,

I updated to 1.3.9 when it were out, but, I think still happens, but I have no idea how it does :(
Is there anything i can do to help?

Apr  4 10:32:06 fastweb roundcube: PHP Warning:  file_get_contents(/home/hosting/dg.pt/webmail/temp/ea569c9341b1ff55fb723b076254a7f8.tmp): failed to open stream: No such file or directory in /home/hosting/dg.pt/webmail/program/steps/mail/get.inc on line 533
Apr  4 11:44:24 fastweb roundcube: PHP Warning:  file_get_contents(/home/hosting/dg.pt/webmail/temp/8b36eb6281a742218a8ff21791a168ac.tmp): failed to open stream: No such file or directory in /home/hosting/dg.pt/webmail/program/steps/mail/get.inc on line 533

**Comment by alecpl** [comment]
The only thing that I can think of is to track the problematic email messages. Following code added on top of get.inc file would log username and GET arguments to logs/console. This way you'll be able to match warning with debug info by the log entries timestamp. Then, if you provide that message source  I could try to reproduce (or at least find precise code execution path) and fix.
```
rcube::console($RCMAIL->get_user_name(), $_GET);
```

**Comment by dddns** [comment]
Hi Alec,

Ok just added, wait some days till i get something and i'll let you know.

==
<?php
rcube::console($RCMAIL->get_user_name(), $_GET);

/**
 +-----------------------------------------------------------------------+
 | program/steps/mail/get.inc                     
==

**Comment by dddns** [comment]
Alec,

For this, i don't have more than the information below.
Is there something usefull?

==
Jun 18 11:15:48 fastweb roundcube: <cj432iru> celia@clientdomain.pt;#012array (#012  '_task' => 'mail',#012  '
_action' => 'get',#012  '_mbox' => 'Sent',#012  '_uid' => '5',#012  '_token' => 'TUTXhZNgnzUHfjo4hzeIEJx3ku1xbS
0E',#012  '_part' => '4',#012  '_embed' => '1',#012  '_mimeclass' => 'image',#012  '_thumb' => '1',#012)
Jun 18 11:15:49 fastweb roundcube: <cj432iru> celia@clientdomain.pt;#012array (#012  '_task' => 'mail',#012  '
_action' => 'get',#012  '_mbox' => 'Sent',#012  '_uid' => '5',#012  '_token' => 'TUTXhZNgnzUHfjo4hzeIEJx3ku1xbS
0E',#012  '_part' => '6',#012  '_embed' => '1',#012  '_mimeclass' => 'image',#012  '_thumb' => '1',#012)
Jun 18 11:15:49 fastweb roundcube: PHP Warning:  file_get_contents(/home/hosting/sss.pt/webmail/temp/220dafb3617aaf280269acf788f036df.tmp): failed to open stream: No such file or directory in /home/hosting/sss.pt/webmail/program/steps/mail/get.inc on line 534
Jun 18 11:15:49 fastweb roundcube: PHP Warning:  file_get_contents(/home/hosting/sss.pt/webmail/temp/e6fc2e4469566f97aad5472021d4645d.tmp): failed to open stream: No such file or directory in /home/hosting/sss.pt/webmail/program/steps/mail/get.inc on line 534
Jun 18 11:15:49 fastweb roundcube: PHP Warning:  file_get_contents(/home/hosting/sss.pt/webmail/temp/89d9db7a93be9f6d2d9463d10610b5b8.tmp): failed to open stream: No such file or directory in /home/hosting/sss.pt/webmail/program/steps/mail/get.inc on line 534
Jun 18 11:15:51 fastweb roundcube: <cj432iru> celia@clientdomain.pt;#012array (#012  '_task' => 'mail',#012  '_frame' => '1',#012  '_mbox' => 'Sent',#012  '_uid' => '5',#012  '_part' => '7',#012  '_action' => 'get',#012  '_extwin' => '1',#012)
Jun 18 11:15:51 fastweb roundcube: <cj432iru> celia@clientdomain.pt;#012array (#012  '_task' => 'mail',#012  '_preload' => '1',#012  '_mbox' => 'Sent',#012  '_uid' => '5',#012  '_part' => '7',#012  '_action' => 'get',#012  '_extwin' => '1',#012)
Jun 18 11:15:51 fastweb roundcube: <cj432iru> celia@clientdomain.pt;#012array (#012  '_task' => 'mail',#012  '_mbox' => 'Sent',#012  '_uid' => '5',#012  '_part' => '7',#012  '_action' => 'get',#012  '_extwin' => '1',#012  '_mimewarning' => '1',#012  '_embed' => '1',#012)
Jun 18 11:16:09 fastweb roundcube: <3qkg04gf> Successful login for celia@clientdomain.pt (ID: 1683) from 62.28.129.209 in session 3qkg04gfi7eklcel7itfqcqq4p
Jun 18 11:16:11 fastweb roundcube: <3qkg04gf> celia@clientdomain.pt;#012array (#012  '_task' => 'mail',#012  '_action' => 'get',#012  '_mbox' => 'INBOX',#012  '_uid' => '22',#012  '_token' => '3o1DWABlHH2lSKlbnIjYpTKxsT8CRrSA',#012  '_part' => '2',#012  '_embed' => '1',#012  '_mimeclass' => 'image',#012)
Jun 18 11:16:11 fastweb roundcube: <3qkg04gf> celia@clientdomain.pt;#012array (#012  '_task' => 'mail',#012  '_action' => 'get',#012  '_mbox' => 'INBOX',#012  '_uid' => '22',#012  '_token' => '3o1DWABlHH2lSKlbnIjYpTKxsT8CRrSA',#012  '_part' => '2',#012  '_embed' => '1',#012  '_mimeclass' => 'image',#012)

**Comment by alecpl** [comment]
It tells us that problem probably could be reproduced with message with UID=5 in celia's Sent folder. Are you able to get that message for review?

**Comment by dddns** [comment]
Alec,

Yes,
Can you help me on how to i identify message with uid 5?

**Comment by alecpl** [comment]
Well, for some imap servers (e.g. Cyrus IMAP) the uid is just a file name in user folder. If that's not the case, you have to use imap to list message headers by uid. E.g.
```
-- first connect and login then
a001 SELECT Sent
a002 UID FETCH 5 (BODY.PEEK[HEADER])
```

**Comment by dddns** [comment]
here you have it:

https://pastebin.com/pWVSSp96

**Comment by alecpl** [comment]
I need the the full email message source. If you can't get it from filesystem use `x UID FETCH 5 (BODY.PEAK[])`.

**Comment by dddns** [comment]
Alec here you have it, untouched raw msg

http://neotrix.decimal.pt/bugs/rawmsg_celia.zip

**Comment by alecpl** [comment]
Ok, but does that message cause these errors in log for you? I'm unable to reproduce. That could mean it's specific to your system not a specific message.

**Comment by alecpl** [comment]
Not enough information.
