### ISSUE TITLE
Password Plugin lists wrong requirements when using zxcvbn

### ISSUE THREAD

**Issue by alienmindbender** [roundcube/roundcubemail#6922]
Hi!

Using zxcvbn adds "Password must include at least one number and one punctuation character." as a requirements to the password change dialog.
But a password like "AcGdgDhhDBPiKK" ist still accepted without any errors.

**Comment by alecpl** [comment]
Fixed.

**Comment by alienmindbender** [comment]
Thank you  for the quick fix!

Not really in relation to the previous bug, but still the same topic.
It's impossible the yield a grade 5 via zxcvbn when enforcing a minimum of 10 chars only.
A password like "@ äl 9hé ," for example is  graded  4 - while "@ äl 9hé , " (added space at the end) would yield a 5.
Should probably be noted in the documentation/configuration.
