### ISSUE TITLE
rouncube need ctype extension

### ISSUE THREAD

**Issue by gwijayas** [roundcube/roundcubemail#7049]
The [install requirement](https://github.com/roundcube/roundcubemail/wiki/Install-Requirements) or installation process didn't mention/didn't check ctype extension as requirement. Some mail message will failed to read. The log is:
```
 PHP Fatal error:  Uncaught Error: Call to undefined function Masterminds\HTML5\Parser\ctype_alpha()
```

php: 7.3.11

**Comment by alecpl** [comment]
I created a ticket (https://github.com/Masterminds/html5-php/issues/173) to remove that dependency. For now we'll update installer and documentation.

**Comment by alecpl** [comment]
Fixed.

**Comment by nextgens** [comment]
FYI https://github.com/roundcube/roundcubemail/wiki/Install-Requirements still doesn't mention ctype
