### ISSUE TITLE
PHP Warning:  preg_replace(): Compilation failed: invalid range in character class at offset 71 in /usr/share/roundcube/program/lib/Roundcube/rcube_vcard.php on line 547

### ISSUE THREAD

**Issue by atrens** [roundcube/roundcubemail#7177]
Moving from php7.2 to php7.3 looks like '\w' is not supported by preg_replace() .. changing occurrences to '[a-zA-Z0-9_]' works around the issue.  

I have version 1.3.6 installed (ubuntu/bionic), and php 7.3.13-1 ..

**Comment by alecpl** [comment]
This was fixed in 1.3.8.

**Comment by atrens** [comment]
Hi Alec,

How was this fixed?  Looking at the latest version of rcube_vcard.php I still see \w in the same two locations where it is causing my issues.

I know that you fixed the \R by replacing it with \r\n .. but you have not fixed the \w.

Please explain if there is some other, more global change that you made to address this.

--Andrew

**Comment by alecpl** [comment]
Sorry, I was too fast, but I need a test case. I never saw that warning, and I'm using PHP 7.4.

According to https://www.php.net/manual/en/regexp.reference.character-classes.php "The character types \d, \D, \s, \S, \w, and \W may also appear in a character class".

**Comment by alecpl** [comment]
Here's your fix https://github.com/roundcube/roundcubemail/commit/24e3977d74e1e1bd7a624. As I've said it was 1.3.8.

**Comment by atrens** [comment]
Thank you Aleksander,

Not what I expected.  I guess the error message is a bit misleading! :)
