### ISSUE TITLE
1.4.2 Skin Chooser Lists Files in skins Folder

### ISSUE THREAD

**Issue by jellykells** [roundcube/roundcubemail#7180]
After updating from 1.3.10 to 1.4.2 the skin chooser shows the custom skin files I have stored in the skins folder.
Unless actual skins can be packaged as a single file, it probably makes sense to only show folders, which was the behavior in 1.3.x

![Screenshot_20200116_075240](https://user-images.githubusercontent.com/42573508/72530535-3281a200-3835-11ea-99dd-e73a8118f44a.png)

**Comment by alecpl** [comment]
Confirmed.

**Comment by alecpl** [comment]
Fixed.

**Comment by meaz** [comment]
I'm sorry @alecpl to comment this closed issue, but I've just tested with 1.4.3, and I still see my files that are in skins folder ( .md file and a .png file)
![skins](https://user-images.githubusercontent.com/13604424/79841318-89a88d00-83b7-11ea-9d0e-26093a283c02.png)

**Comment by alecpl** [comment]
Not for me. Make sure you upgraded properly.

**Comment by meaz** [comment]
my bad indeed. Sorry about that.
