### ISSUE TITLE
Double scroll bar when answering to a mail with many lines

### ISSUE THREAD

**Issue by uli-heller** [roundcube/roundcubemail#7500]
I'm on 1.4.7 and "elastic".

When I answer an email containing lots of lines (like for example the output of `ls -l /bin/`), a new window will open up
having two scroll bars:

![image](https://user-images.githubusercontent.com/1677414/88147308-4ac7e480-cbfd-11ea-851d-f527005a1e01.png)

Jumping to the top of the window and pressing a key makes the inner scroll bar disappear:

![image](https://user-images.githubusercontent.com/1677414/88147243-3d125f00-cbfd-11ea-83c4-30bd4b6ac05b.png)

**Comment by alecpl** [comment]
Fixed.

**Comment by uli-heller** [comment]
Thx a lot, that was pretty fast ;)

**Comment by tw-** [comment]
I'm on 1.4.9 and elastic - but problem is still (or again?) the same.
