### ISSUE TITLE
CORB issue when configuring Roundcube with Outlook

### ISSUE THREAD

**Issue by teodor-k96** [roundcube/roundcubemail#7923]
I'm currently trying to configure Roundcube to work with Outlook's IMAP/SMTP through OAuth. If I don't use Oauth it seems be working fine but when trying to set up the authentication I get a CORB error in the console. The app lets you pick an account and reaches the consent screen. However once I hit "yes" for consent it redirects back to the Roundcube login page instead of inside the Outlook account. I tried everything I could think of and basically started brute forcing the setting at this point so I'm pretty lost as to what the problem might be. Any input would be greatly appreciated.

This is the 'config.inc.php' config that I currently have:

```
$config['oauth_provider'] = 'outlook';
$config['oauth_provider_name'] = 'Outlook.com';
$config['oauth_client_id'] = "-||-||-";
$config['oauth_client_secret'] = "-||-||-";
$config['oauth_auth_uri'] = "https://login.microsoftonline.com/common/oauth2/v2.0/authorize";
$config['oauth_token_uri'] = "https://login.microsoftonline.com/common/oauth2/v2.0/token";
$config['oauth_identity_uri'] = "https://graph.microsoft.com/v1.0/me";
$config['oauth_identity_fields'] = null;
$config['oauth_scope'] = "https://outlook.office.com/IMAP.AccessAsUser.All https://outlook.office.com/SMTP.Send User.Read offline_access";
$config['oauth_auth_parameters'] = ['nonce' => mt_rand(), 'prompt' => 'consent'];
$config['oauth_login_redirect'] = true;
$config['oauth_verify_peer'] = true;
   
// of IMAP host (no prefix or port) and SMTP server e.g. \['imap.example.com' => 'smtp.example.net'\]
$config['smtp_server'] = 'tls://smtp.office365.com';

// SMTP port. Use 25 for cleartext, 465 for Implicit TLS, or 587 for STARTTLS (default)
$config['smtp_port'] = 587;

$config['default_host'] = 'ssl://outlook.office365.com';

// TCP port used for IMAP connections
$config['default_port'] = 993;
```

Pictures of what appears in the console after a redirect back to the login page: 
![corb](https://user-images.githubusercontent.com/51955652/110349136-0f1e4580-803b-11eb-9280-619a856e8781.png)

Error from Mozilla: 
_The resource from “https://login.microsoftonline.com/common/oauth2/v2.0/authorize?response_type=code&client_id=1111111111&scope=https%3A%2F%2Foutlook.office.com%2FIMAP.AccessAsUser.All+https%3A%2F%2Foutlook.office.com%2FSMTP.Send+User.Read+offline_access&redirect_uri=https%3A%2F%2Fsocialcloudwm.com%2Fwebmailoffice365%2Findex.php%2Flogin%2Foauth&state=pJFjCaPDvbNG&nonce=1971951749&prompt=consent” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff)._

**Comment by alecpl** [comment]
@thomascube When I just use `https://my-rouncube-host/index.php/login/oauth` URL the page is broken. I guess, at least this we should fix?

**Comment by thomascube** [comment]
The CORB issue seems to be caused by https://login.microsoftonline.com/ and not by Roundcube. The rendering of the Roundcube login page was fixed in commit 8fdf37bf2.

The reason why your OAuth login with outlook.com doesn't work might be the missing value for the `oauth_identity_fields` config option. This defaults to `email` and Microsoft probably uses another field in the identity token. Try set `$config['oauth_identity_fields'] = ['email', 'userPrincipalName'];` as shown in the example in `defaults.inc.php` file.

**Comment by teodor-k96** [comment]
> The CORB issue seems to be caused by https://login.microsoftonline.com/ and not by Roundcube. The rendering of the Roundcube login page was fixed in commit [8fdf37b](https://github.com/roundcube/roundcubemail/commit/8fdf37bf21b8459d2504bfb9fdcb284049774807).
> 
> The reason why your OAuth login with outlook.com doesn't work might be the missing value for the `oauth_identity_fields` config option. This defaults to `email` and Microsoft probably uses another field in the identity token. Try set `$config['oauth_identity_fields'] = ['email', 'userPrincipalName'];` as shown in the example in `defaults.inc.php` file.

**Comment by teodor-k96** [comment]
> The CORB issue seems to be caused by https://login.microsoftonline.com/ and not by Roundcube. The rendering of the Roundcube login page was fixed in commit [8fdf37b](https://github.com/roundcube/roundcubemail/commit/8fdf37bf21b8459d2504bfb9fdcb284049774807).
> 
> The reason why your OAuth login with outlook.com doesn't work might be the missing value for the `oauth_identity_fields` config option. This defaults to `email` and Microsoft probably uses another field in the identity token. Try set `$config['oauth_identity_fields'] = ['email', 'userPrincipalName'];` as shown in the example in `defaults.inc.php` file.

That didnt work. Still the same result at the end. But thanks anyway. I am currently corresponding with Microsoft Support Team in order to solve the issue. Hopefully, if we get to solution, I will leave a feedback.
