### ISSUE TITLE
XOAUTH2 authentication on refresh

### ISSUE THREAD

**Issue by ll4strw** [roundcube/roundcubemail#8388]
Hello everybody.

I have roundcube v1.5.2 configured to authenticate users via OAuth with my identity provider. It does work rather well I should say, however I have been observing the following behavior.

A user logs in by being redirected to my identity provider login page (`$config['oauth_login_redirect'] = true;`). An authorization token with validity of 5 minutes is issued and stored in the browser. If the user requests a refresh of his inbox or roundcube automatically refreshes the inbox view, then roundcube tries contacting to the IMAP server to authenticate that user via XOAUTH2 using an expired token, which clearly results in an authentication error.
In particular, roundcube displays a popup dialog saying `AUTHENTICATE XOAUTH2: A0001 NO [AUTHENTICATIONFAILED] Authentication failed.`. Would not be better to redirect the user to the identity provider login page?

**Comment by thomascube** [comment]
Please note that an "authorization token" is not an access token. The latter also isn't stored in your browser but on the Roundcube server only. Please check if your identity provider issues a refresh token alongside with the access token. Refresh tokens are used by Roundcube to request new access tokens once they expire. Some identity providers require a certain scope to be requested in order to issue refresh tokens.

**Comment by ll4strw** [comment]
Many thanks indeed for your prompt reply. I can confirm my identity provider (keycloak) issues both an access token and a refresh token as you said. Regardless of the token type used to access an inbox and its duration, which might differ from implementation to implementation, would not be better in this instance to replace the rc error popups to redirect the "expired" user to the provider's login page? This would improve the user experience.
PS: Where does rc store the identity tokens?

**Comment by ll4strw** [comment]
I would like to report also the following related behavior. 
I have an access token with validity 5 mins and a refresh token with validity 8 hours. What I observe is that around 5 mins after a successful login, although the reported error popup is shown (presumably because the access  token is expired), the client just keeps working fine if the alert is dismissed or ignored (presumably because a refresh token is used?).
Nonetheless, RC fills up the error logs with failed XOAUTH2 attempts around every 5 mins.
I am wondering if this is supposed to be the expected behavior.

**Comment by azmeuk** [comment]
I can confirm this still happens with roundcube 1.6
By enabling debug logging on dovecot, I can see that the token it received is expired.

**Comment by azmeuk** [comment]
I think I found the reason. My IDP was misconfigured and gave different values for the token `expires_in` claim, and the [JWT access token](https://www.rfc-editor.org/rfc/rfc9068) `exp` claim.

I had a `expires_in` value of 10 days and a `exp` value of 1 hour. Roundcube was refering to `expires_in` and considered the token to be still active, but dovecot read the `exp` claim in the JWT and considered it expired.

**Comment by azmeuk** [comment]
I use [canaille](https://canaille.yaal.coop/). We fixed the inconsistency between `exp` and `expires_in` in a new release, and since I do not have the roundcube authentication error anymore.

**Comment by alecpl** [comment]
There's been a lot of OAuth changes in Roundcube 1.7. Is there still an issue with 1.7-beta?

**Comment by ryan77627** [comment]
@alecpl Perhaps.... I am just beginning to migrate email servers and set all of this up, so this very well may be a misconfiguration on my end yet. However, on the current nightly (docker tag `226b978337e7`) I am observing the above behavior. I log in via OAuth and after approx. 5 minutes my session is invalidated. Decreasing the access token lifetime to 1 minute also shortens my Roundcube session to 1 minute, after which I am logged out due to an invalid session.

I use Authentik for my identity provider and Stalwart for my email provider, will look into the above later today to see if it also has some discrepancies in `exp` and `expires_in`.

EDIT: As I post that, I have come to realize it is most likely a misconfiguration:
`roundcube-1  | oauth: <fba07a7c> DEBUG: [ip=192.168.16.1 (X-Forwarded-For: xxx.xxx.xxx.xxx) sub=- ses=-] no refresh token found in the payload`

...that would do it. Apologies for the noise. I can now verify this is in fact not an issue and refreshing the session works properly in the nightly tag listed above :)
