### ISSUE TITLE
PHP deprecated functions errors

### ISSUE THREAD

**Issue by InputOutputZ** [roundcube/roundcubemail#8584]
Hi there,

Another minor bug here I report, when I open draft email with empty message content and attachment I get:-

```
[21-Jun-2022 12:23:18 UTC] PHP Deprecated:  strlen(): Passing null to parameter #1 ($string) of type string is deprecated in /program/actions/mail/show.php on line 789
[21-Jun-2022 12:23:18 UTC] PHP Deprecated:  preg_replace_callback(): Passing null to parameter #3 ($subject) of type array|string is deprecated in /program/lib/Roundcube/rcube_string_replacer.php on line 225
```

Without attachment and empty message content I get:-

`[21-Jun-2022 12:23:18 UTC] PHP Deprecated:  str_replace(): Passing null to parameter #2 ($replace) of type array|string is deprecated in /program/lib/Roundcube/rcube.php on line 608`

Notice, I use RC 1.6, PHP 8.1.3 and Apache/2.5.1.

With thanks.

Zakaria.

**Comment by alecpl** [comment]
Fixed.

**Comment by jeensg** [comment]
Hey, thank you for fixing. I just updated now to 1.6 and still get this error, but I think for a different file:
`[25-Aug-2022 15:53:19 Europe/Berlin] PHP Deprecated:  strlen(): Passing null to parameter #1 ($string) of type string is deprecated in /var/www/roundcube/vendor/pear/mail_mime/Mail/mime.php on line 984
[25-Aug-2022 15:53:19 Europe/Berlin] PHP Deprecated:  strlen(): Passing null to parameter #1 ($string) of type string is deprecated in /var/www/roundcube/vendor/pear/mail_mime/Mail/mime.php on line 985
[25-Aug-2022 15:53:19 Europe/Berlin] PHP Deprecated:  strlen(): Passing null to parameter #1 ($string) of type string is deprecated in /var/www/roundcube/vendor/pear/mail_mime/Mail/mime.php on line 1354
[25-Aug-2022 15:53:19 Europe/Berlin] PHP Deprecated:  strlen(): Passing null to parameter #1 ($string) of type string is deprecated in /var/www/roundcube/vendor/pear/mail_mime/Mail/mime.php on line 1355`
and
`[25-Aug-2022 15:22:57 Europe/Berlin] PHP Deprecated:  DOMImplementation::createDocument(): Passing null to parameter #2 ($qualifiedName) of type string is deprecated in /var/www/roundcube/vendor/masterminds/html5/src/HTML5/Parser/DOMTreeBuilder.php on line 178`

If it's not related I can also start a new report. Thanks anyway!

**Comment by alecpl** [comment]
@jeensg It's not related, but these warnings in external packages were already fixed, you have to update the dependencies.

**Comment by jeensg** [comment]
> @jeensg It's not related, but these warnings in external packages were already fixed, you have to update the dependencies.

Thanks for your answer. Since I updated with the "complete" package from [here](https://roundcube.net/download/), I thought the dependencies are already in there!? If not, how is that possible?

**Comment by alecpl** [comment]
#8642
