### ISSUE TITLE
Template Help Page, that goes over basic roundcube Usage.

### ISSUE THREAD

**Issue by Jieiku** [roundcube/roundcubemail#8898]
Some of our clients are elderly people, and figuring out how to do things that are simply intuitive for me, are often difficult for them.

One Example, the "collected recipients" feature while very useful, was confusing a new client, he had no idea where the extra recipients were coming from, some of them he did not even recognize, and to make matters worse he could not figure out how to delete a contact. You might suggest just turn it off, but then they want to know why its not remembering their previously communicated with people like many of the big email services do... so it's a fine line to walk.

I had to send this picture:

![contact-delete-edit](https://user-images.githubusercontent.com/106644/215468356-5c99e918-003b-4636-81fe-737d5f7e0886.png)

One Idea I had was maybe there could be a small trash can and Pen Icon right aligned on the actual contact buttons, I think if the icons were made very simple it could still look elegant. Another options might be to put the icon with the 3 dots "..."  which has the contact options like edit and delete. Anything that makes it more intuitive for people coming from other services like hotmail, yahoo, gmail, etc is a good thing in my opinion.

![icons](https://user-images.githubusercontent.com/106644/215468389-7bf09cd6-9d7c-4e43-a02f-0a9df9b3e0b4.png)

I also sent this picture showing where to turn the setting on or off:

![2023-01-29_18-35-48](https://user-images.githubusercontent.com/106644/215377730-538c7d6c-01a2-4148-b09d-f7c9ea5ea60d.png)

I am getting a little off track here, but my idea was to put some of the things new users may have difficulty with into the Help page, currently when I click it nothing happens, So I will look into what is needed to create that page, but a basic page that comes with roundcube might be a good idea, and pictures are gold!

![2023-01-29_18-55-26](https://user-images.githubusercontent.com/106644/215377895-7424e2da-3f9b-4857-8c10-bbcb31b428ea.png)

Assuming such a basic help page does not already exist, let me know if you would like help creating one.

**Comment by alecpl** [comment]
The help plugin should open https://docs.roundcube.net/doc/help/1.1/en_US/ (but it could be configured to something else) so there might be some bug in the plugin.

**Comment by Jieiku** [comment]
Thanks, I will investigate that!

**Comment by alecpl** [comment]
I pushed a fix for the Help plugin. I'm not sure it fixes your issue, but there definitely was a bug in the menu.

**Comment by Jieiku** [comment]
Did not fix my issue, but I had not even checked the developer console yet.

It seems it fetches this data from the internet, I am wondering if it would be better to include the help documentation with the roundcube application?

![2023-02-19_12-39-16](https://user-images.githubusercontent.com/106644/219973986-c9ca3134-2571-464b-a1a0-f4f4a5a01aec.png)

Is the help documentation files available anywhere? I could try hosting a local copy.

**Comment by alecpl** [comment]
I think all you need is to set `$config['help_source'] = 'https://docs.roundcube.net/doc/help/1.1/%l/';` I.e. make sure to use `https://`. And yes, it can be set to any location.
