### ISSUE TITLE
HTTP 2.0 compatibility issues

### ISSUE THREAD

**Issue by InputOutputZ** [roundcube/roundcubemail#8982]
Hi there,

In some instances, Roundcube fails session authentication and its expected to do this. I found some logic it has compatibility issues with HTTP 1.0 and 2.0 and couldn't find a solution and I suspect that this is a bug needs fixing because when user gets logged out, in index.php execution reaches unauthenticated hook and returns the following:-

```
    if ($plugin['http_code'] == 401) {
        header('HTTP/1.0 401 Unauthorized');
    }
```

In android Chrome/112.0.5615.47 browser it throws net::ERR_HTTP_RESPONSE_CODE_FAILURE but when I change HTTP/1.0 to HTTP/2.0 the problem its resolved.

I didnt find way where I effectively can upgrade HTTP 1.0 to HTTP 2.0 whenever browser offers support within Roundcube despite I have it set in the web server to upgrade but it seems Roundcube header call force the browser to use HTTP 1.0 when the webserver expects 2.0.

For now, my mitigation its I set the following and the problem is fixed but not sure from long term if it is the right way.

```
    if ($plugin['http_code'] == 401) {
        header('HTTP/2.0 401 Unauthorized');
    }
```

I hope my explanation is clear and looking forward for your input. 

With thanks.

Zakaria.

**Comment by alecpl** [comment]
Fixed.

**Comment by DoobleD** [comment]
Hi folks, thanks for the fix! I see it has been merged to master in May 2023 but still isn't in the releases? I used to patch releases with a20445f but since release 1.6.6 the patch fails.

**Comment by DoobleD** [comment]
Hi, a new version [1.6.8 ](https://github.com/roundcube/roundcubemail/releases/tag/1.6.8) has been released but this still doesn't appear to be in it, is that normal? @alecpl?

The patch can no longer be applied to the latest release due to changes in the sources.

**Comment by alecpl** [comment]
I don't plan to backport this to 1.6.

**Comment by DoobleD** [comment]
Thank you for your replu @alecpl. Is there any particular reason for not backporting the fix?

**Comment by InputOutputZ** [comment]
> Thank you for your replu [@alecpl](https://github.com/alecpl). Is there any particular reason for not backporting the fix?

Milestone for 1.7-beta I think.
