### ISSUE TITLE
ldapi unix socket broken in 1.6

### ISSUE THREAD

**Issue by user12921** [roundcube/roundcubemail#8990]
"ldapi://" is currently not working as an addressbook host, it gets scrambled to "ldap://ldapi://:389".

Quick and dirty fix:
```
--- program/lib/Roundcube/rcube_ldap.php.orig   2023-04-25 19:32:46.961019828 +0200
+++ program/lib/Roundcube/rcube_ldap.php        2023-04-25 20:01:25.421688675 +0200
@@ -307,9 +307,11 @@
         // see http://www.php.net/manual/en/function.ldap-connect.php
         foreach ((array) $this->prop['hosts'] as $host) {
             // Parse host specification into the format expected by Net_LDAP3 (ldap_connect)
-            list($host, $scheme, $port) = rcube_utils::parse_host_uri($host, 389, 636);
+            if (!(strncmp($host, 'ldapi://', 8) === 0)) {
+                list($host, $scheme, $port) = rcube_utils::parse_host_uri($host, 389, 636);
 
-            $host = sprintf('%s://%s:%d', $scheme === 'ldaps' ? 'ldaps' : 'ldap', $host, $port);
+                $host = sprintf('%s://%s:%d', $scheme === 'ldaps' ? 'ldaps' : 'ldap', $host, $port);
+            }
 
             $this->ldap->config_set('use_tls', $scheme === 'tls');
```

**Comment by alecpl** [comment]
I wasn't aware such a thing existed ;)

**Comment by alecpl** [comment]
Fixed.

**Comment by user12921** [comment]
I am sorry to report, after just updating to 1.6.9, that the problem is still present for me.

My config:
$config['ldap_public'] = array (
  'addressbook1' =>
  array (
    'name' => 'XXXX',
    'hosts' =>
    array (
      0 => 'ldapi://',
    ),
...

Syslog:
Nov 19 20:01:31 XXXX roundcube[41654]: <pr5vsfbf> C: Connect [ldap://ldapi://:-1:389]
Nov 19 20:01:31 XXXX roundcube[41654]: <pr5vsfbf> S: NOT OK
Nov 19 20:01:31 XXXX roundcube[41654]: <pr5vsfbf> PHP Error: Could not connect to LDAP (GET /?_task=addressbook&_action=search&_q=walter&_headers=name%2Cfirstname%2Csurname%2Cemail&_scope=base&_remote=1&_unlock=loading1732042891130&_=1732041790895)
Nov 19 20:01:31 XXXX roundcube[41654]: <pr5vsfbf> LDAP Error: Could not connect to any LDAP server in /var/www/roundcubemail-1.6.9/program/lib/Roundcube/rcube_ldap.php on line 510 (GET /?_task=addressbook&_action=search&_q=walter&_headers=name%2Cfirstname%2Csurname%2Cemail&_scope=base&_remote=1&_unlock=loading1732042891130&_=1732041790895)

**Comment by alecpl** [comment]
It may be as simple as this:
```patch
--- a/program/lib/Roundcube/rcube_ldap.php
+++ b/program/lib/Roundcube/rcube_ldap.php
@@ -305,7 +305,9 @@ class rcube_ldap extends rcube_addressbook
             // Parse host specification into the format expected by Net_LDAP3 (ldap_connect)
             [$host, $scheme, $port] = rcube_utils::parse_host_uri($host, 389, 636);
 
-            $host = sprintf('%s://%s:%d', $scheme === 'ldaps' ? 'ldaps' : 'ldap', $host, $port);
+            if ($scheme != 'ldapi') {
+                $host = sprintf('%s://%s:%d', $scheme === 'ldaps' ? 'ldaps' : 'ldap', $host, $port);
+            }
 
             $this->ldap->config_set('use_tls', $scheme === 'tls');
 
```
@user12921 can you confirm?

**Comment by user12921** [comment]
Sorry, forgot to give an update.
I just now upgraded to 1.6.11 and the problem is fixed.
Thanks
