### ISSUE TITLE
Depecrecation in session_set_save_handler() method with PHP 8.4

### ISSUE THREAD

**Issue by vmario89** [roundcube/roundcubemail#9763]
### Prerequisites

- [x] I have [searched](https://github.com/roundcube/roundcubemail/issues?q=is%3Aissue) for duplicate or closed issues
- [x] I can recreate the issue with all plugins disabled

### Describe the issue

Hi,
since updating Roundcube 1.6.9 to use PHP8.4 i get a spam flood of deprecations in the session handler. The issue persists, even when i disable all plugins.

In the install notes it's recommended to have PHP greater 7.3 - i did not read anything about upper limit of the version. https://github.com/roundcube/roundcubemail/blob/release-1.6/INSTALL

this comes from nginx error log file:
```
2025/02/03 10:38:24 [error] 3918174#3918174: *236159 FastCGI sent in stderr: "PHP message: PHP Deprecated:  session_set_save_handler(): Providing individual callbacks instead of an object implementing SessionHandlerInterface is deprecated in /var/www/roundcube/program/lib/Roundcube/rcube_session.php on line 119" while reading response header from upstream, client: REDACTED, server: REDACTED.REDACTED.REDACTED, request: "GET /robots.txt HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm/php84.sock:", host: REDACTED
```

thank you!

### What browser(s) are you seeing the problem on?

Other

### What version of PHP are you using?

8.4

### What version of Roundcube are you using?

1.6.9

**Comment by alecpl** [comment]
This has been solved in master, but the change is quite big, so I don't plan a backport. You should be able to configure PHP to do not log such errors.

Some other deprecation warnings are also expected in 1.6 under PHP >= 8.4.

**Comment by abcbarryn** [comment]
When will the fix be in a release?
In the meantime I added:
`error_reporting(E_ALL ^ E_DEPRECATED);`
to the file
`roundcube/program/lib/Roundcube/rcube_session.php`
in front of line 119, as shown:
```
        ini_set('session.serialize_handler', 'php');

        // set custom functions for PHP session management
        error_reporting(E_ALL ^ E_DEPRECATED);
        session_set_save_handler(
            [$this, 'open'],
            [$this, 'close'],
            [$this, 'read'],
            [$this, 'sess_write'],
            [$this, 'destroy'],
            [$this, 'gc']
        );
    }
```

Patch file:
```
--- roundcube/program/lib/Roundcube/rcube_session.php     2025-04-22 18:06:59.412533980 -0400
+++ roundcube/program/lib/Roundcube/rcube_session.php   2025-04-22 18:09:41.457614925 -0400
@@ -117,4 +117,5 @@

         // set custom functions for PHP session management
+        error_reporting(E_ALL ^ E_DEPRECATED);
         session_set_save_handler(
             [$this, 'open'],
```

**Comment by ShaiMagal** [comment]
Hi, @alecpl ,

what version of RC will include full PHP 8.4 support?

I tested latest 1.6.11, but still not implemented:
`PHP Deprecated:  session_set_save_handler(): Providing individual callbacks instead of an object implementing SessionHandlerInterface is deprecated in roundcubemail-1.6.11/program/lib/Roundcube/rcube_session.php on line 119`

Thank you :)

**Comment by alecpl** [comment]
I don't plan any changes to 1.6 regarding better PHP 8.4 support.

**Comment by abcbarryn** [comment]
Then in 1.7? Or is RoundCube no longer updating to stay in support with new PHO versions?

**Comment by alecpl** [comment]
The next major, whether it is 1.7 or 2.0 is not decided yet.

**Comment by hrdgit** [comment]
Any update ?
