### ISSUE TITLE
Internal error after auto refresh

### ISSUE THREAD

**Issue by dsvf** [roundcube/roundcubemail#9957]
### Prerequisites

- [x] I have [searched](https://github.com/roundcube/roundcubemail/issues?q=is%3Aissue) for duplicate or closed issues
- [ ] I can recreate the issue with all plugins disabled

### Describe the issue

Running the 1.7 Beta. Everything works normally, but after a while, the tab content is replaced by the error:

Oops... something went wrong!
An internal error has occurred. Your request cannot be processed at this time.

I would guess that this happens upon an autoreload. See the php error message attached below.

### What browser(s) are you seeing the problem on?

Firefox

### What version of PHP are you using?

8.2

### What version of Roundcube are you using?

1.7beta

### PHP errors

[17-Aug-2025 16:30:02 UTC] PHP Fatal error:  Uncaught TypeError: html::quote(): Argument #1 ($str) must be of type string, null given, called in /var/www/html/rc/program/include/rcmail_output_html.php on line 1653 and defined in /var/www/html/rc/program/lib/Roundcube/html.php:392
Stack trace:
#0 /var/www/html/rc/program/include/rcmail_output_html.php(1653): html::quote()
#1 [internal function]: rcmail_output_html->xml_command()
#2 /var/www/html/rc/program/include/rcmail_output_html.php(1339): preg_replace_callback()
#3 /var/www/html/rc/program/include/rcmail_output_html.php(816): rcmail_output_html->parse_xml()
#4 /var/www/html/rc/program/include/rcmail_output_html.php(650): rcmail_output_html->parse()
#5 /var/www/html/rc/program/include/rcmail.php(293): rcmail_output_html->send()
#6 /var/www/html/rc/public_html/index.php(265): rcmail->action_handler()
#7 {main}
  thrown in /var/www/html/rc/program/lib/Roundcube/html.php on line 392

**Comment by dsvf** [comment]
The "faulty" URL being called is https://mail.example.com/?_task=mail&_action=refresh

**Comment by johndoh** [comment]
The refresh action does not usually involve the `rcmail_output_html` class because its an ajax request so it uses `rcmail_output_json`. The error you have posted points to an issue passing a variable from a template. Please confirm the issue persists with all plugins disabled and also that you are using the Elastic skin.

**Comment by alecpl** [comment]
The circumstances aren't clear, but I fixed the fatal error.

**Comment by dsvf** [comment]
For completeness' sake - I deactivated all plugins and the error persisted, I switched to elastic (from LARRY) and it went away.
